### ISSUE TITLE
Helm Charts is missing enroute-crds

### ISSUE THREAD

**Issue by crnastena** [saarasio/enroute#64]
Following this guide [EnRoute Kubernetes Ingress Gateway](https://getenroute.io/docs/getting-started-enroute-ingress-controller/) breaks on 2nd step:

    # setup helm repo
    % helm repo add saaras https://getenroute.io
    % helm repo update

    # command only returns two results for saaras, enroute-crds is missing.
    % helm search repo
    saaras/enroute                                  0.4.0           0.8.0           EnRoute API Gateway                               
    saaras/service-policy                           0.3.0           0.8.0           Service L7 Policy using EnRoute API Gateway       

    % helm install saaras/enroute-crds --generate-name
    Error: failed to download "saaras/enroute-crds" (hint: running `helm repo update` may help)

So either guide is out of date (Feb, 2020) or something else is up.

**Comment by saarasio** [comment]
Thank you @crnastena for reporting this. The guide looks outdated and we will update it.

We will verify this again, but just installing EnRoute using the helm chart should work without having to install the CRDs.

**Comment by crnastena** [comment]
Installing just enroute throws error about enroutedemo namespace missing. I tried adding namespace beforehand but that led to other issues. 

I'll wait for the updated guide.

**Comment by chintan8saaras** [comment]
fbf3feb2ea26754d6f249d64c82ed3b6b4908bc9 Moved ```GlobalConfig``` to it's own file.

The first time ```helm install``` created an instance of ```GlobalConfig```. The subsequent ```helm upgrade``` tried to create the ```GlobalConfig``` again (since it got moved to it's own file)

Helm charts were failing in creation of ```GlobalConfig``` since they were already created during the first invocation of the command.

The fix was to use the flag ```--set service.createGlobalConfig=false``` in the ```helm upgrade``` command

Fixed the guide referenced in this bug and re-ran the complete example. Attached is a successful run of a log.

[success-run.txt](https://github.com/saarasio/enroute/files/7103471/success-run.txt)

Also added a graphical representation of artifacts created during different stages of helm command invocation to provide more insight into steps. 

![EnRouteGettingStartedSteps2](https://user-images.githubusercontent.com/45217805/131954431-49eebd18-28e1-4856-83da-6c1efbc22f03.jpeg)

**Comment by saarasio** [comment]
@crnastena Let us know if you run into any issues, we have also verified the guide and pushed out a new version of EnRoute to work with the latest version of Envoy v1.19.1

Running through the getting started guide you mentioned in the first comment should use the latest version of EnRoute along with Envoy v1.19.1

Thank you for reporting the bug!

**Comment by crnastena** [comment]
@saarasio I went through the steps in the new guide and they are working ok. Not a big deal but output for the first helm search repo is showing older versions `0.4.0` and `0.3.0` for enroute and service-policy respectively. 

![image](https://user-images.githubusercontent.com/1594571/131987744-e26114a7-0ef2-4ee9-b534-027ee0dc9ac9.png)

SSL parts of the guide I had to skip as I am running tests locally on docker/minikube and I don't get external IP/domain. I am doing port-forwarding to access httpbin service.

```
# in one terminal tab
% kubectl port-forward -n enroutedemo service/enroute 8900:80
Forwarding from 127.0.0.1:8900 -> 8080
Forwarding from [::1]:8900 -> 8080
Handling connection for 8900
Handling connection for 8900

# in other terminal tab
% curl -i http://127.0.0.1:8900/get                             
HTTP/1.1 200 OK
server: envoy
date: Fri, 03 Sep 2021 09:50:56 GMT
content-type: application/json
content-length: 270
access-control-allow-origin: *
access-control-allow-credentials: true
x-envoy-upstream-service-time: 3
vary: Accept-Encoding

{
  "args": {}, 
  "headers": {
    "Accept": "*/*", 
    "Host": "127.0.0.1:8900", 
    "User-Agent": "curl/7.64.1", 
    "X-Envoy-Expected-Rq-Timeout-Ms": "15000", 
    "X-Envoy-Internal": "true"
  }, 
  "origin": "172.17.0.8", 
  "url": "http://127.0.0.1:8900/get"
}
```

Thanks for all the help.
Cheers!

**Comment by saarasio** [comment]
@crnastena Perhaps ```helm repo update``` might help to fetch newer versions of the charts. Here is an excerpt from success-run.txt --

```
ubuntu@instance-20210310-1357-dev:~$ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "saaraslocal" chart repository
...Successfully got an update from the "jetstack" chart repository

...Successfully got an update from the "saaras" chart repository
Update Complete. ⎈Happy Helming!⎈
ubuntu@instance-20210310-1357-dev:~$ helm search repo
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
jetstack/cert-manager           v1.5.3          v1.5.3          A Helm chart for cert-manager
jetstack/cert-manager-istio-csr v0.2.3          v0.2.1          A Helm chart for istio-csr
saaras/enroute                  0.4.1           0.8.0           EnRoute API Gateway
saaras/service-policy           0.3.1           0.8.0           Service L7 Policy using EnRoute API Gateway
saaraslocal/enroute             0.4.1           0.8.0           EnRoute API Gateway
saaraslocal/service-policy      0.3.1           0.8.0           Service L7 Policy using EnRoute API Gateway
```

**Comment by crnastena** [comment]
Heya @saarasio issue is not with fetching but documentation, that is what the screenshot is showing.

**Comment by saarasio** [comment]
@crnastena Appreciate you following up on this, we've fixed the article now. Thanks!
