### ISSUE TITLE
Helm Chart: Support Namespace Configuration in helm chart

### ISSUE THREAD

**Issue by chintan8saaras** [saarasio/enroute#67]
Issue reported by @aeimer

1. The chart
    - does not support other namespaces than `enroutedemo` which is quite ugly
    - it creates the namespace in any case; helm-chart should not create their own namespaces; better use `helm install [...] --create-namespace` or create the NS externally (like we do)
    - No HPA in place
    - Not all options that may be interesting could be adapted or were not working
    - No proper labels were used
    - namespaces were set in the yamls
 2. You can create that on your own:
     ```
     curl -o enroute.tgz https://raw.githubusercontent.com/aeimer/enroute/update-helmchart/helm-chart/enroute-0.5.0.tgz
     helm install -n test someenroute enroute.tgz --dry-run
     ```
3. I had to write this to get your service up and running for testing/evaluating purposes. So I couldn't test it extensively. btw you could add helm chart testing to your ci.

**Comment by chintan8saaras** [comment]
Verified that the new chart works after the namespace changes to ```ServiceAccount```

Verified - (1) Filters (2) SSL Cert installation with new chart

TODO: Still need to verify some flags
TODO: Need to add updated commands to the getting started article

**Comment by aeimer** [comment]
@chintan8saaras Also I removed the hello-enroute things, as I think this should be in a separate helm chart IMHO.

**Comment by chintan8saaras** [comment]
Verified the changes with tests.

**Comment by chintan8saaras** [comment]
Verified that the new chart is uploaded and re-ran the tests

**Comment by chintan8saaras** [comment]
Updated getting started guide on website -

https://getenroute.io/docs/getting-started-enroute-ingress-controller/
